#!/usr/bin/env bash
set -e # exit immediately upon error(s)

# Directory in which this script is located.
SCRIPT_DIR="$(dirname -- "$(readlink -f -- "$0")")"

# Name of the jar containing the chocosolver application.
CHOCOSOLVER_JAR="chocosolver.jar"

# execute chocosolver from the same directory
# we set the maximum heap size to a default of 6GB,
# because the default is too small on some runners
# (e.g., GitHub Actions) and causes the solver to fail
java -Xmx${CHOCOSOLVER_HEAP_SIZE:-6144m} -jar "$SCRIPT_DIR/$CHOCOSOLVER_JAR" $@
