// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 Free & Fair
// See LICENSE.md for details

//! Top-level actor for the Election Administration Server.
//!
//! This actor manages concurrent voter authentication sessions and routes
//! messages to the appropriate sub-actors. It also handles session
//! lifecycle including timeouts and manual aborts.

// TODO: consider boxing structs in large enum variants to improve performance
// currently ignored for code simplicity until performance data is analyzed.
#![allow(clippy::large_enum_variant)]

use super::sub_actors::voter_authentication::VoterAuthenticationActor;
use super::sub_actors::voter_authentication::VoterAuthenticationInput;
use super::sub_actors::voter_authentication::VoterAuthenticationOutput;

use crate::cryptography::SigningKey;
use crate::elections::ElectionHash;
use crate::messages::AuthReqMsg;
use crate::messages::ProtocolMsg;

use std::collections::HashMap;
use std::time::{Duration, Instant};

/// Unique identifier generated by the top-level actor for each newly
/// initiated voter authentication request. A 64-bit unsigned integer
/// ought be sufficient; otherwise, we may alternatively use [`u128`]
/// or a [`String`].
///
/// All network and Authentication Service (AS) messages are expected
/// to be tied to an [`AuthReqId`]. Hence, this identifier is also used
/// as a second parameter in subprotocol inputs & outputs to facilitate
/// routing of network/AS messages to the correct sub-actor that deals
/// with the respective authentication request.
pub type AuthReqId = u64;

// =============================================================================
// Commands and I/O Types
// =============================================================================

/// Commands that can be sent to the Election Administration Server.
///
/// Note that [`AuthReqMsg`] messages must not be directly forwarded
/// to a sub-actor via a [`SubprotocolInput::VoterAuthentication`]
/// but wrapped into a [`Command::StartVoterAuthentication`] command.
///
/// This is because the top-level actor has to do some additional work
/// for those messages, i.e., by generating a fresh request id, creating
/// a new [`VoterAuthenticationActor`] sub-actor, etc., before routing
/// them to the newly created sub-actor that handles the authentication
/// request from thereon.
#[derive(Debug, Clone)]
pub enum Command {
    /// Begin processing a voter authentication request from the network.
    ///
    /// The top-level actor assigns a fresh [`AuthReqId`] and creates a
    /// new [`VoterAuthenticationActor`] to handle the request.
    StartVoterAuthentication(AuthReqMsg),

    /// Abort an in-progress voter authentication request.
    ///
    /// If the given [`AuthReqId`] is not found the output will be
    /// [`SubprotocolOutput::RequestNotFound`] rather than an error.
    AbortVoterAuthentication(AuthReqId),
}

/// Input forwarded to a voter authentication sub-actor.
#[derive(Debug, Clone)]
pub enum SubprotocolInput {
    /// Input for a [`VoterAuthenticationActor`] sub-actor.
    VoterAuthentication(VoterAuthenticationInput),
}

/// Input to the Election Administration Server actor.
#[derive(Debug, Clone)]
pub enum ActorInput {
    /// A command from the host application.
    Command(Command),

    /// Input forwarded to the sub-actor identified by [`AuthReqId`].
    SubprotocolInput(SubprotocolInput, AuthReqId),
}

// =============================================================================
// Output Types
// =============================================================================

/// Output from the Election Administration Server actor.
#[derive(Debug, Clone)]
pub enum SubprotocolOutput {
    /// Output from a [`VoterAuthenticationActor`] sub-actor.
    VoterAuthentication(VoterAuthenticationOutput, AuthReqId),

    /// The request was manually aborted.
    Aborted(AuthReqId),

    /// The request may have expired.
    RequestNotFound(AuthReqId),
}

// =============================================================================
// Top-Level Actor
// =============================================================================

/// The top-level Election Administration Server actor.
///
/// This actor manages concurrent voter authentication sessions using a
/// HashMap and routes messages to the appropriate sub-actors. Completed
/// and timed-out sessions are purged automatically after each input.
#[derive(Debug, Clone)]
pub struct ElectionAdminServerActor {
    // --- Shared Configuration ---
    /// The election hash for this election.
    election_hash: ElectionHash,

    /// The EAS's signing key for signing authorization messages.
    eas_signing_key: SigningKey,

    // --- Session Management ---
    /// Maps request IDs to active voter authentication sub-actors.
    requests: HashMap<AuthReqId, VoterAuthenticationActor>,

    /// The next unused request ID.
    next_available_id: AuthReqId,

    /// How long a sub-actor may be idle before it is considered expired.
    network_timeout: Duration,

    // --- Authentication Service (AS) Credentials ---
    /// The Authentication Service project ID, shared with sub-actors.
    as_project_id: String,

    /// The Authentication Service API key, shared with sub-actors.
    as_api_key: String,
}

impl ElectionAdminServerActor {
    /// Create a new [`ElectionAdminServerActor`] instance.
    ///
    /// # Arguments
    /// * `election_hash` - The election hash for this election
    /// * `eas_signing_key` - The EAS's signing key for authorization messages
    /// * `network_timeout` - How long a sub-actor may be idle before expiry
    /// * `as_project_id` - The Authentication Service project ID
    /// * `as_api_key` - The Authentication Service API key
    ///
    /// # Returns
    /// A new `ElectionAdminServerActor` with no active authentication sessions.
    pub fn new(
        election_hash: ElectionHash,
        eas_signing_key: SigningKey,
        network_timeout: Duration,
        as_project_id: String,
        as_api_key: String,
    ) -> Self {
        Self {
            election_hash,
            eas_signing_key,
            requests: HashMap::new(),
            next_available_id: 0,
            network_timeout,
            as_project_id,
            as_api_key,
        }
    }

    /// Process an input to the Election Administration Server.
    ///
    /// This is the main entry point for all interactions with the EAS.
    /// After handling the input, expired and completed sub-actors are
    /// automatically purged.
    ///
    /// # Arguments
    /// * `input` - The input to process
    ///
    /// # Returns
    /// * `Ok(output)` - The output from processing the input
    /// * `Err(msg)` - If an unexpected error occurs
    pub fn process_input(&mut self, input: ActorInput) -> Result<SubprotocolOutput, String> {
        let result = match input {
            ActorInput::Command(command) => self.handle_command(command),

            ActorInput::SubprotocolInput(subprotocol_input, auth_req_id) => {
                self.handle_subprotocol_input(subprotocol_input, auth_req_id)
            }
        };

        // The state update merely removes subactors that have timed out.
        self.handle_state_update();

        result
    }

    /// Handle a command from the host application.
    fn handle_command(&mut self, command: Command) -> Result<SubprotocolOutput, String> {
        match command {
            Command::StartVoterAuthentication(auth_req_msg) => {
                // We create a fresh id and sub-actor for each incoming
                // authentication request, even if an authentication
                // request with the same public key is currently being
                // processed or has already been processed.
                let fresh_id: AuthReqId = self.next_available_id;

                match self.next_available_id.checked_add(1) {
                    Some(next) => self.next_available_id = next,
                    None => panic!(
                        "We ran out of 64-bit authentication request ids. This ought be impossible (?)"
                    ),
                }

                // We can assume that we have an unused id here.
                assert!(!self.requests.contains_key(&fresh_id));

                let sub_actor = VoterAuthenticationActor::new(
                    self.election_hash,
                    self.eas_signing_key.clone(),
                    self.as_project_id.clone(),
                    self.as_api_key.clone(),
                );

                self.requests.insert(fresh_id, sub_actor);

                let subactor_input =
                    VoterAuthenticationInput::NetworkMessage(ProtocolMsg::AuthReq(auth_req_msg));

                let output = self
                    .requests
                    .get_mut(&fresh_id)
                    .unwrap() // ought never panic
                    .process_input(subactor_input);

                Ok(SubprotocolOutput::VoterAuthentication(output, fresh_id))
            }

            Command::AbortVoterAuthentication(auth_req_id) => {
                if self.requests.remove(&auth_req_id).is_some() {
                    Ok(SubprotocolOutput::Aborted(auth_req_id))
                } else {
                    Ok(SubprotocolOutput::RequestNotFound(auth_req_id))
                }
            }
        }
    }

    /// Forward a subprotocol input to the sub-actor identified by `auth_req_id`.
    fn handle_subprotocol_input(
        &mut self,
        subprotocol_input: SubprotocolInput,
        auth_req_id: AuthReqId,
    ) -> Result<SubprotocolOutput, String> {
        match subprotocol_input {
            SubprotocolInput::VoterAuthentication(subactor_input) => {
                match subactor_input {
                    VoterAuthenticationInput::NetworkMessage(ProtocolMsg::AuthReq(_)) => {
                        panic!(
                            "unexpected authentication request message sent directly to sub-actor; issue a StartVoterAuthentication(AuthReqMsg) command instead"
                        )
                    }

                    VoterAuthenticationInput::NetworkMessage(_) => {
                        if self.requests.contains_key(&auth_req_id) {
                            let output = self
                                .requests
                                .get_mut(&auth_req_id)
                                .unwrap() // ought never fail
                                .process_input(subactor_input);

                            Ok(SubprotocolOutput::VoterAuthentication(output, auth_req_id))
                        } else {
                            Ok(SubprotocolOutput::RequestNotFound(auth_req_id))
                        }
                    }

                    VoterAuthenticationInput::AuthServiceMessage(_) => {
                        if self.requests.contains_key(&auth_req_id) {
                            let output = self
                                .requests
                                .get_mut(&auth_req_id)
                                .unwrap() // ought never fail
                                .process_input(subactor_input);

                            Ok(SubprotocolOutput::VoterAuthentication(output, auth_req_id))
                        } else {
                            Ok(SubprotocolOutput::RequestNotFound(auth_req_id))
                        }
                    }

                    VoterAuthenticationInput::BiographicalInfoOk {
                        voter_pseudonym: _,
                        ballot_style: _,
                    } => {
                        if self.requests.contains_key(&auth_req_id) {
                            let output = self
                                .requests
                                .get_mut(&auth_req_id)
                                .unwrap() // ought never fail
                                .process_input(subactor_input);

                            Ok(SubprotocolOutput::VoterAuthentication(output, auth_req_id))
                        } else {
                            Ok(SubprotocolOutput::RequestNotFound(auth_req_id))
                        }
                    }

                    VoterAuthenticationInput::BiographicalInfoInvalid(_) => {
                        if self.requests.contains_key(&auth_req_id) {
                            let output = self
                                .requests
                                .get_mut(&auth_req_id)
                                .unwrap() // ought never fail
                                .process_input(subactor_input);

                            Ok(SubprotocolOutput::VoterAuthentication(output, auth_req_id))
                        } else {
                            Ok(SubprotocolOutput::RequestNotFound(auth_req_id))
                        }
                    }
                }
            }
        }
    }

    /// The state update purges completed and expired requests.
    fn handle_state_update(&mut self) {
        self.purge_completed_requests();
        self.purge_expired_requests();
    }

    /// Purge all sub-actors that have completed.
    fn purge_completed_requests(&mut self) {
        self.requests.retain(|_, request| !request.has_completed());
    }

    /// Purge all sub-actors that have timed out.
    fn purge_expired_requests(&mut self) {
        let now = Instant::now();
        self.requests
            .retain(|_, request| now - request.get_time_of_last_input() <= self.network_timeout);
    }
}
