# .github/workflows/test-validity-of-threat-model.yml
# Author: Daniel M. Zimmerman
# Created: 2025-01-22
# Modified: 2026-06-25

# This workflow tests the validity of the threat model by building
# the database and the PDF.

name: Test Validity of Threat Model

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'models/threat-model/**'
      - '.github/workflows/test-validity-of-threat-model.yml'

  workflow_dispatch:

jobs:
  threat-model:
    name: Build Threat Model Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: sudo apt-get install build-essential

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Python Dependencies for Threat Model
        run: |
          cd models/threat-model
          pip install -r requirements.txt

      - name: Run `view` Smoke Test in Threat Model Directory
        run: |
          cd models/threat-model
          make view

      - name: Render Threat Model HTML
        run: |
          cd models/threat-model
          make html

      - name: Prepare Threat Model PDF Dependencies
        run: |
          cd models/threat-model
          make latex

      - name: Render Threat Model PDF
        uses: FreeAndFair/latex-action@v4
        with:
          working_directory: models/threat-model
          root_file: threat-model.tex

      - name: Save the Generated Threat Model PDF
        uses: actions/upload-artifact@v7
        with:
          name: generated_threat_model_pdf
          path: models/threat-model/threat-model.pdf

      - name: Save the Generated Threat Model HTML
        uses: actions/upload-artifact@v7
        with:
          name: generated_threat_model_html
          path: models/threat-model/threat-model.html
