# .github/workflows/test-validity-of-refinements-paper.yml
# Author: Daniel M. Zimmerman
# Created: 2025-02-20
# Modified: 2026-06-25

# This workflow tests the validity of the "Refinements Among
# High Level Models" paper by building it. It also saves the
# resulting artifact.

name: Test Validity of "Refinements Among High-Level Models" Paper

on:
  # We run this for pushes to `main`, manual workflow dispatch, and
  # on PRs.
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'docs/papers/refinements_among_high_level_models/**'
      - '.github/workflows/test-validity-of-refinements-paper.yml'

  workflow_dispatch:

jobs:
  refinements-paper:
    name: Run Latexmk on Paper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Latexmk in Paper Directory
        uses: FreeAndFair/latex-action@v4
        with:
          working_directory: docs/papers/refinements_among_high_level_models
          root_file: refinements_paper.tex

      - name: Save the Generated PDF
        uses: actions/upload-artifact@v7
        with:
          name: refinements_among_high_level_models_paper
          path: docs/papers/refinements_among_high_level_models/refinements_paper.pdf
